/**
 * Naano Internationalization (i18n) Controller
 * High-fidelity bidirectional English <-> Spanish translation engine.
 * Supports data-i18n attributes, selector-level mappings, animated word-reveals,
 * and state persistence across all application pages.
 */

export const STORAGE_KEY = 'naano_lang';

export const translations = {
  EN: {
    // Nav
    'nav.for_companies': 'For companies',
    'nav.for_creators': 'For creators',
    'nav.for_agencies': 'For agencies',
    'nav.how_it_works': 'How it works',
    'nav.resources': 'Resources',
    'nav.signin': 'Sign in',
    'nav.signup': 'Sign up',
    'nav.res_pricing': 'Creator pricing',
    'nav.res_brief': 'Free brief generator',
    'nav.res_cases': 'Case study: BlogSEO',
    'nav.res_reports': 'Reports',

    // Hero
    'hero.badge': 'Where B2B brands work with creators',
    'hero.title': 'The B2B LinkedIn <br class="hero-title-break" />Creator Marketplace<span class="hero-dot">.</span>',
    'hero.sub': 'Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.',
    'hero.cta_primary': 'Launch a campaign',
    'hero.cta_secondary': 'See how Naano works',
    'hero.trusted_by': 'Trusted by modern B2B teams',

    // Quote
    'quote.role': 'CEO, Zmirov Communication',
    'quote.agency': 'Influence agency',

    // Marketplace
    'market.eyebrow': 'The Naano creator marketplace',
    'market.title': 'Work with all the best creators.',
    'market.copy': 'Find the right B2B voices, compare their audience fit, and book every collaboration from one place.',
    'market.signal1_title': '3,000+ vetted creators',
    'market.signal1_sub': 'Specialist B2B voices, ready to collaborate.',
    'market.signal2_title': 'Across 100 countries',
    'market.signal2_sub': 'Local expertise with genuinely global reach.',
    'market.signal3_title': 'Matched to your buyers',
    'market.signal3_sub': 'Audience fit comes before follower count.',

    // Testimonials / Case Study
    'proof.video_eyebrow': 'VIDEO TESTIMONIAL',
    'proof.case_eyebrow': 'CASE STUDY',
    'proof.title': 'Real teams. Measurable pipeline.',
    'proof.sub': 'See how B2B teams turn creator trust into attributable demand with Naano.',
    'proof.video_quote': '“Naano became one of our fastest acquisition channels. We know exactly what every creator brings.”',
    'proof.case_title': 'How BlogSEO turned creator content into product signups',
    'proof.case_copy': 'BlogSEO briefed SEO & SaaS creators on LinkedIn and X, then traced every trial back to the post that drove it, all in Naano.',
    'proof.stat1_label': 'creators activated',
    'proof.stat2_label': 'qualified clicks',
    'proof.stat3_label': 'trials started',
    'proof.read_case': 'Read case study',
    'proof.trust_eyebrow': 'TRUSTED BY TEAMS AT',

    // Results
    'results.eyebrow': 'THE RESULTS',
    'results.title': 'Proven across thousands<br class="lp-results-title-br" /> of campaigns.',
    'results.stat_imp': 'Impressions generated',
    'results.stat_leads': 'Leads generated',
    'results.stat_creators': 'Creators on Naano',
    'results.stat_posts': 'Posts published',
    'results.lbl_imp': 'Impressions',
    'results.lbl_clicks': 'Clicks',
    'results.lbl_leads': 'Leads',
    'results.lbl_view_post': 'View post',
    'results.lbl_for': 'For',
    'results.cta_btn': 'Get started',
    'results.cta_sub': "Start free. Pay per post when you're ready.",

    // Pricing
    'pricing.title': 'Pricing<span class="lp-pricing-dot">.</span>',
    'pricing.lead': 'Start free. Upgrade when you want your time back.',
    'pricing.desc': 'Choose whether you want to run creator campaigns in-house or have Naano operate them.',
    'pricing.self_eyebrow': 'SELF-SERVE',
    'pricing.self_title': 'Run it yourself.',
    'pricing.self_copy': 'For teams that want the infrastructure to run creator campaigns in-house.',
    'pricing.self_cost': '€0',
    'pricing.self_period': '/ month',
    'pricing.self_f1': 'Creator marketplace access',
    'pricing.self_f2': 'AI-powered brief creation',
    'pricing.self_f3': 'Track clicks, companies and pipeline',
    'pricing.self_f4': 'Automatic creator payouts',
    'pricing.self_cta': 'Start for free',
    'pricing.managed_eyebrow': 'MANAGED CAMPAIGNS',
    'pricing.managed_title': 'Get your time back.',
    'pricing.managed_copy': 'For teams that want Naano to operate their creator channel end to end.',
    'pricing.managed_cost': 'Custom quote',
    'pricing.managed_f1': 'Campaign strategy and positioning',
    'pricing.managed_f2': 'Creator sourcing and coordination',
    'pricing.managed_f3': 'Brief creation and campaign launch',
    'pricing.managed_f4': 'Reporting and optimisation',
    'pricing.managed_cta': 'Book a campaign call',
    'pricing.footnote': 'Campaign spend is separate. No lock-in. Cancel anytime.',

    // FAQs
    'faq.title': 'Frequently <br />asked <br />questions<span class="lp-faq-dot">.</span>',
    'faq.sub': 'Everything you need to know before getting started.',
    'faq.callout_lbl': 'Still have questions?',
    'faq.callout_link': 'Talk to our team',
    'faq.q1': 'What is Naano?',
    'faq.a1': 'Naano is a B2B LinkedIn creator marketplace: companies discover and book vetted creators for sponsored LinkedIn campaigns, each at a fixed price per post set by the creator. The marketplace spans creators from niche voices with around 1,000 followers to established B2B creators with audiences of several hundred thousand.',
    'faq.q2': 'How does Naano find the right creators?',
    'faq.a2': 'Our matching engine scores every creator on audience fit, category relevance and engagement quality across LinkedIn, X and YouTube, so you rank creators by who actually reaches your buyers, not by follower count.',
    'faq.q3': 'Which networks do you support?',
    'faq.a3': 'LinkedIn, X and YouTube today, with more on the way. You can compare creators and track performance across every network in one place.',
    'faq.q4': 'How does per-post pricing work?',
    'faq.a4': 'Campaigns start from €20 per published post, you only pay for posts that go live, with no retainer. Prefer a hands-off setup? Done for you adds our team executing everything end to end.',
    'faq.q5': 'How does attribution work?',
    'faq.a5': 'Naano places a tracking pixel at every stage of the funnel, so each click, lead, pipeline and revenue is tied back to the exact creator and post that drove it.',
    'faq.q6': 'Do you handle creator payouts?',
    'faq.a6': 'Yes. Approve content and pay every creator in one click, securely via Stripe Connect, invoices and approvals are handled for you.',
    'faq.q7': "What's the difference between Free and Done for you?",
    'faq.a7': 'Free gives your team the platform to source creators and run simple campaigns yourselves. Done for you adds hands-on execution by the Naano team, sourcing, briefs, reporting and optimisation.',
    'faq.q8': 'Can I upgrade or cancel anytime?',
    'faq.a8': 'Absolutely. Plans are month-to-month, you can upgrade, downgrade or cancel whenever you like.',

    // Ready to Launch
    'launch.eyebrow': 'READY TO LAUNCH?',
    'launch.title': 'Your next creator campaign starts here.',
    'launch.subtitle': 'Get a clear creator strategy, campaign format and estimated budget for your next launch.',
    'launch.badge': 'CAMPAIGN STRATEGY CALL',
    'launch.card_title': '30-minute working session',
    'launch.card_desc': 'Leave with a concrete plan for your next creator campaign.',
    'launch.feat_strategy': 'Creator strategy',
    'launch.feat_format': 'Campaign format',
    'launch.feat_budget': 'Budget recommendation',
    'launch.cta_book': 'Book a campaign call',
    'launch.hint': 'Pick a time on the next page.',
    'launch.secondary': 'Prefer to start yourself? <strong>Start for free →</strong>',
    'launch.footnote': 'Trusted by B2B teams building creator-led acquisition.',

    // Footer
    'footer.tagline': 'The B2B LinkedIn creator marketplace.',
    'footer.col_product': 'PRODUCT',
    'footer.col_resources': 'RESOURCES',
    'footer.col_company': 'COMPANY',
    'footer.col_legal': 'LEGAL',
    'footer.copyright': '© 2026 Naano Technologies Inc. All rights reserved.',

    // Register Page
    'reg.title': 'Create your account',
    'reg.sub': 'First, who are you here as?',
    'reg.opt_creator_title': "I'm a creator",
    'reg.opt_creator_desc': 'Get paid to create LinkedIn content for B2B brands you actually use.',
    'reg.opt_brand_title': "I'm a brand",
    'reg.opt_brand_desc': 'Find creators, launch campaigns, and trace real pipeline back to each post.',
    'reg.already_account': 'Already have an account? <a href="/login?reauth=1" class="auth-signin-link">Sign in</a>',
    'reg.stmt_title': 'One platform. Two sides.',
    'reg.stmt_copy': "Creators get paid to post. B2B brands get real pipeline. Pick where you fit and we'll set the rest up in a couple of minutes.",

    'reg.back_roles': 'Back to role selection',
    'reg.back_account': 'Back to account creation',
    'reg.back_details': 'Back to company details',
    'reg.step1_4': 'STEP 1 OF 4',
    'reg.step2_4': 'STEP 2 OF 4',
    'reg.step3_4': 'STEP 3 OF 4',
    'reg.step4_4': 'STEP 4 OF 4',
    'reg.step1_3': 'STEP 1 OF 3',
    'reg.step2_3': 'STEP 2 OF 3',
    'reg.step3_3': 'STEP 3 OF 3',

    'reg.creator_join_title': 'Join Naano',
    'reg.creator_join_sub': 'Connect your LinkedIn profile to get discovered by B2B brands.',
    'reg.creator_btn_linkedin': 'Continue with LinkedIn',
    'reg.creator_btn_email': 'Continue with Work Email',
    'reg.creator_terms': "By continuing, you agree to Naano's Terms of Service and Privacy Policy.",

    'reg.creator_step2_title': 'Verify your profile details',
    'reg.creator_step2_sub': 'We extracted this from your LinkedIn. Edit anything that looks off.',
    'reg.lbl_name': 'Display Name',
    'reg.lbl_headline': 'Headline',
    'reg.lbl_followers': 'Audience size',
    'reg.lbl_topic': 'Primary Topic',
    'reg.lbl_rate': 'Post Rate (€)',
    'reg.btn_continue_preview': 'Continue to Card Preview',

    'reg.creator_step3_title': 'Generating your creator card...',
    'reg.creator_step3_sub': 'Analyzing your LinkedIn profile and audience demographics.',
    'reg.btn_enter_workspace': 'Enter Workspace',

    'reg.brand_step1_title': 'Create brand account',
    'reg.brand_step1_sub': 'Access vetted B2B creators and track attributed revenue.',
    'reg.brand_btn_google': 'Continue with Google',
    'reg.lbl_work_email': 'Work Email',
    'reg.lbl_company_name': 'Company Name',
    'reg.lbl_company_website': 'Company Website',
    'reg.btn_continue_onboarding': 'Continue to Onboarding',

    'reg.brand_step2_title': 'Value proposition & ICP',
    'reg.brand_step2_sub': 'Our AI uses this to match you with the right creators and auto-draft briefs.',
    'reg.lbl_value_prop': 'What does your product do? (Value Proposition)',
    'reg.lbl_target_audience': 'Target Audience / ICPs (Select all that apply)',
    'reg.lbl_starter_brief': 'Starter Creator Brief (Auto-generated)',
    'reg.btn_launch_matching': 'Find Matching Creators',

    'reg.brand_step3_title': 'AI creator matching in progress',
    'reg.brand_step3_sub': 'Scanning 4,800+ verified B2B profiles matching your ICP criteria.',
    'reg.btn_explore_dashboard': 'Enter Brand Dashboard',

    'reg.card_preview_eyebrow': 'YOUR MARKETPLACE CARD',
    'reg.card_preview_title': 'Build a card brands can trust.',
    'reg.card_preview_copy': 'It updates live with your profile, analytics, positioning and price.',
    'reg.lbl_url': 'LinkedIn Profile URL',
    'reg.brand_stmt_title': 'Creators. Brands. Results.',
    'reg.brand_stmt_copy': 'Run LinkedIn creator campaigns that drive real business - discover creators, track performance, pay in one click.',
    'reg.brand_stmt_sub': 'Built for B2B marketing teams',
    'reg.brand_mic_query': 'What would you like to see?',

    // Login
    'login.tab_creator': "I'm a Creator",
    'login.tab_brand': "I'm a Brand",
    'login.creator_title': 'Welcome back, Creator',
    'login.creator_sub': 'Sign in to manage your creator card, active deals, and payouts.',
    'login.brand_title': 'Welcome back, Brand',
    'login.brand_sub': 'Sign in to manage creator briefs, active campaigns, and pipeline analytics.',
    'login.btn_linkedin': 'Continue with LinkedIn',
    'login.btn_google': 'Continue with Google',
    'login.signup_note': 'Don\'t have an account yet? <a href="/register" class="auth-signin-link" id="login-signup-link">Sign up</a>',

    // Workspace
    'ws.back': 'Back to onboarding',
    'ws.eyebrow': 'Creator workspace',
    'ws.title': 'Good to see you, Waqar',
    'ws.subtitle': 'Your creator activity, at a glance.',
    'ws.metric_reach': 'PUBLIC POST REACH',
    'ws.metric_reach_desc': 'Waiting for public post data',
    'ws.metric_posts': 'PUBLIC POSTS',
    'ws.metric_posts_desc': 'Original LinkedIn posts found',
    'ws.metric_eng': 'PUBLIC ENGAGEMENTS',
    'ws.metric_eng_desc': 'Reactions, comments and reposts',
    'ws.metric_followers': 'LINKEDIN FOLLOWERS',
    'ws.metric_followers_desc': 'Imported from the public profile',
    'ws.card_title': 'Your creator card',
    'ws.card_sub': 'This is how brands discover your positioning and collaboration offer.',
    'ws.btn_open': 'Open card',
    'ws.btn_copy': 'Copy card link',
    'ws.btn_share': 'Share my card',
    'ws.badge_active': 'Active Creator',
    'ws.badge_top': 'Top 5% Engagement',
    'ws.guide_title': 'Your launch guide',
    'ws.guide_sub': '1 of 1 steps complete',
    'ws.guide_step_title': 'Card and price ready',
    'ws.guide_step_sub': 'Your positioning and offer are ready to review.',
    'ws.guide_step_complete': 'Complete',
    'ws.collabs_title': 'Active collaborations',
    'ws.collabs_sub': 'Everything currently moving from brief to publication.',
    'ws.collabs_empty': 'No active collaborations.',
    'ws.collabs_see_all': 'See all',
    'ws.collabs_th_brand': 'Brand',
    'ws.collabs_th_status': 'Status',
    'ws.collabs_th_action': 'Next action',
    'ws.collabs_th_due': 'Due',
    'ws.collabs_th_net': 'Net',
    'ws.opps_title': 'Recommended opportunities',
    'ws.opps_sub': 'The 3 campaigns that best match your audience.',
    'ws.opps_explore': 'Explore',
    'ws.opp_match_sub': 'Main campaign · strong match',
    'ws.card_no_data': 'No post data available',
    'ws.card_data_lbl': 'Data',
    'ws.card_status_pending': 'Pending',
    'ws.card_stat_followers': 'Followers',
    'ws.card_stat_est_imp': 'Est. impressions',
    'ws.card_stat_cost': 'Chosen cost',
    'ws.floating_assistant': 'What can I help you find?',
  },

  ES: {
    // Nav
    'nav.for_companies': 'Para empresas',
    'nav.for_creators': 'Para creadores',
    'nav.for_agencies': 'Para agencias',
    'nav.how_it_works': 'Cómo funciona',
    'nav.resources': 'Recursos',
    'nav.signin': 'Iniciar sesión',
    'nav.signup': 'Registrarse',
    'nav.res_pricing': 'Precios de creadores',
    'nav.res_brief': 'Generador de briefs gratis',
    'nav.res_cases': 'Caso de éxito: BlogSEO',
    'nav.res_reports': 'Informes y estudios',

    // Hero
    'hero.badge': 'Donde las marcas B2B colaboran con creadores',
    'hero.title': 'El marketplace de creadores <br class="hero-title-break" />de LinkedIn para B2B<span class="hero-dot">.</span>',
    'hero.sub': 'Encuentra los creadores en quienes tus compradores confían, lanza campañas en días y atribuye clics, leads y pipeline a cada publicación.',
    'hero.cta_primary': 'Lanzar una campaña',
    'hero.cta_secondary': 'Cómo funciona Naano',
    'hero.trusted_by': 'Elegido por equipos B2B líderes',

    // Quote
    'quote.role': 'CEO, Zmirov Communication',
    'quote.agency': 'Agencia de influencia',

    // Marketplace
    'market.eyebrow': 'El marketplace de creadores de Naano',
    'market.title': 'Trabaja con los mejores creadores.',
    'market.copy': 'Descubre las voces B2B ideales, analiza la afinidad de su audiencia y contrata cada colaboración en un solo lugar.',
    'market.signal1_title': 'Más de 3.000 creadores verificados',
    'market.signal1_sub': 'Voces B2B especializadas, listas para colaborar.',
    'market.signal2_title': 'En más de 100 países',
    'market.signal2_sub': 'Experiencia local con alcance verdaderamente global.',
    'market.signal3_title': 'Alineados con tus compradores',
    'market.signal3_sub': 'La afinidad de audiencia va antes que el número de seguidores.',

    // Testimonials / Case Study
    'proof.video_eyebrow': 'TESTIMONIO EN VÍDEO',
    'proof.case_eyebrow': 'CASO DE ÉXITO',
    'proof.title': 'Equipos reales. Pipeline medible.',
    'proof.sub': 'Descubre cómo los equipos B2B convierten la confianza en creadores en demanda medible con Naano.',
    'proof.video_quote': '“Naano se convirtió en uno de nuestros canales de captación más rápidos. Sabemos exactamente qué aporta cada creador.”',
    'proof.case_title': 'Cómo BlogSEO convirtió el contenido de creadores en registros de producto',
    'proof.case_copy': 'BlogSEO coordinó creadores de SEO y SaaS en LinkedIn y X, y atribuyó cada prueba de producto directamente al post que la generó en Naano.',
    'proof.stat1_label': 'creadores activados',
    'proof.stat2_label': 'clics cualificados',
    'proof.stat3_label': 'pruebas iniciadas',
    'proof.read_case': 'Leer caso de éxito',
    'proof.trust_eyebrow': 'EQUIPOS QUE CONFÍAN EN NOSOTROS',

    // Results
    'results.eyebrow': 'LOS RESULTADOS',
    'results.title': 'Demostrado en miles<br class="lp-results-title-br" /> de campañas.',
    'results.stat_imp': 'Impresiones generadas',
    'results.stat_leads': 'Leads generados',
    'results.stat_creators': 'Creadores en Naano',
    'results.stat_posts': 'Posts publicados',
    'results.lbl_imp': 'Impresiones',
    'results.lbl_clicks': 'Clics',
    'results.lbl_leads': 'Leads',
    'results.lbl_view_post': 'Ver publicación',
    'results.lbl_for': 'Para',
    'results.cta_btn': 'Empezar ahora',
    'results.cta_sub': 'Empieza gratis. Paga por publicación cuando estés listo.',

    // Pricing
    'pricing.title': 'Precios<span class="lp-pricing-dot">.</span>',
    'pricing.lead': 'Empieza gratis. Mejora tu plan cuando quieras recuperar tu tiempo.',
    'pricing.desc': 'Elige si prefieres gestionar tus campañas internamente o dejar que Naano las opere por ti.',
    'pricing.self_eyebrow': 'AUTOSERVICIO',
    'pricing.self_title': 'Gestiónalo tú mismo.',
    'pricing.self_copy': 'Para equipos que necesitan la infraestructura para lanzar campañas de creadores in-house.',
    'pricing.self_cost': '0 €',
    'pricing.self_period': '/ mes',
    'pricing.self_f1': 'Acceso al marketplace de creadores',
    'pricing.self_f2': 'Creación de briefs asistida por IA',
    'pricing.self_f3': 'Rastreo de clics, empresas y pipeline',
    'pricing.self_f4': 'Pagos automáticos a creadores',
    'pricing.self_cta': 'Empezar gratis',
    'pricing.managed_eyebrow': 'CAMPAÑAS GESTIONADAS',
    'pricing.managed_title': 'Recupera tu tiempo.',
    'pricing.managed_copy': 'Para equipos que quieren que Naano gestione su canal de creadores de principio a fin.',
    'pricing.managed_cost': 'Presupuesto a medida',
    'pricing.managed_f1': 'Estrategia y posicionamiento de campaña',
    'pricing.managed_f2': 'Búsqueda y coordinación de creadores',
    'pricing.managed_f3': 'Creación de briefs y lanzamiento',
    'pricing.managed_f4': 'Informes periódicos y optimización',
    'pricing.managed_cta': 'Agendar llamada de campaña',
    'pricing.footnote': 'El presupuesto de campaña es independiente. Sin permanencia. Cancela cuando quieras.',

    // FAQs
    'faq.title': 'Preguntas <br />frecuentes<span class="lp-faq-dot">.</span>',
    'faq.sub': 'Todo lo que necesitas saber antes de empezar.',
    'faq.callout_lbl': '¿Aún tienes preguntas?',
    'faq.callout_link': 'Habla con nuestro equipo',
    'faq.q1': '¿Qué es Naano?',
    'faq.a1': 'Naano es un marketplace de creadores B2B en LinkedIn: las empresas descubren y contratan creadores verificados para campañas patrocinadas, cada uno a un precio fijo por publicación definido por el creador. Contamos con perfiles desde 1,000 seguidores hasta figuras consagradas con cientos de miles.',
    'faq.q2': '¿Cómo encuentra Naano a los creadores indicados?',
    'faq.a2': 'Nuestro motor de matching califica a cada creador por afinidad de audiencia, relevancia temática y tasa de interacción en LinkedIn, X y YouTube, para que priorices creadores que realmente impactan a tus compradores y no solo por número de seguidores.',
    'faq.q3': '¿Qué redes son compatibles?',
    'faq.a3': 'LinkedIn, X y YouTube hoy, con más integraciones en camino. Puedes comparar creadores y monitorizar el rendimiento en todas las redes desde un único lugar.',
    'faq.q4': '¿Cómo funciona el precio por publicación?',
    'faq.a4': 'Las colaboraciones comienzan desde 20 € por publicación aprobada; solo pagas por el contenido publicado, sin cuotas fijas mensuales. ¿Prefieres que lo hagamos por ti? El servicio Gestionado incluye ejecución integral por nuestro equipo.',
    'faq.q5': '¿Cómo funciona la atribución?',
    'faq.a5': 'Naano implementa un píxel de seguimiento en cada fase del funnel, vinculando cada clic, lead y pipeline generado al creador y post específico que lo produjo.',
    'faq.q6': '¿Gestionan los pagos a los creadores?',
    'faq.a6': 'Sí. Aprueba el contenido y paga a cada creador con un solo clic de forma segura mediante Stripe Connect; las facturas y liquidaciones se gestionan automáticamente.',
    'faq.q7': '¿Cuál es la diferencia entre Gratis y Gestionado?',
    'faq.a7': 'El plan Gratis te da la plataforma para encontrar creadores y operar tus campañas. El servicio Gestionado añade ejecución personalizada por especialistas de Naano: selección, redacción de briefs, informes y optimización.',
    'faq.q8': '¿Puedo cambiar de plan o cancelar en cualquier momento?',
    'faq.a8': 'Totalmente. Los planes son mensuales, puedes subir, bajar de nivel o cancelar en cualquier momento sin penalizaciones.',

    // Ready to Launch
    'launch.eyebrow': '¿LISTO PARA LANZAR?',
    'launch.title': 'Tu próxima campaña de creadores empieza aquí.',
    'launch.subtitle': 'Obtén una estrategia clara, formato de campaña y presupuesto estimado para tu próximo lanzamiento.',
    'launch.badge': 'SESIÓN ESTRATÉGICA DE CAMPAÑA',
    'launch.card_title': 'Sesión de trabajo de 30 minutos',
    'launch.card_desc': 'Sal con un plan de acción concreto para tu próxima campaña de creadores.',
    'launch.feat_strategy': 'Estrategia de creadores',
    'launch.feat_format': 'Formato de campaña',
    'launch.feat_budget': 'Recomendación presupuestaria',
    'launch.cta_book': 'Agendar llamada de campaña',
    'launch.hint': 'Elige fecha y hora en el siguiente paso.',
    'launch.secondary': '¿Prefieres empezar por tu cuenta? <strong>Empieza gratis →</strong>',
    'launch.footnote': 'Con la confianza de equipos B2B líderes en captación con creadores.',

    // Footer
    'footer.tagline': 'El marketplace de creadores de LinkedIn para B2B.',
    'footer.col_product': 'PRODUCTO',
    'footer.col_resources': 'RECURSOS',
    'footer.col_company': 'EMPRESA',
    'footer.col_legal': 'LEGAL',
    'footer.copyright': '© 2026 Naano Technologies Inc. Todos los derechos reservados.',

    // Register Page
    'reg.title': 'Crea tu cuenta',
    'reg.sub': 'Primero, ¿cómo deseas unirte?',
    'reg.opt_creator_title': 'Soy creador',
    'reg.opt_creator_desc': 'Recibe pagos por crear contenido en LinkedIn para marcas B2B que realmente usas.',
    'reg.opt_brand_title': 'Soy una marca',
    'reg.opt_brand_desc': 'Encuentra creadores, lanza campañas y atribuye pipeline real a cada publicación.',
    'reg.already_account': '¿Ya tienes una cuenta? <a href="/login?reauth=1" class="auth-signin-link">Inicia sesión</a>',
    'reg.stmt_title': 'Una plataforma. Dos lados.',
    'reg.stmt_copy': 'Los creadores reciben pagos por publicar. Las marcas B2B generan pipeline real. Elige tu rol y configuraremos el resto en un par de minutos.',

    'reg.back_roles': 'Volver a selección de rol',
    'reg.back_account': 'Volver a crear cuenta',
    'reg.back_details': 'Volver a datos de empresa',
    'reg.step1_4': 'PASO 1 DE 4',
    'reg.step2_4': 'PASO 2 DE 4',
    'reg.step3_4': 'PASO 3 DE 4',
    'reg.step4_4': 'PASO 4 DE 4',
    'reg.step1_3': 'PASO 1 DE 3',
    'reg.step2_3': 'PASO 2 DE 3',
    'reg.step3_3': 'PASO 3 DE 3',

    'reg.creator_join_title': 'Únete a Naano',
    'reg.creator_join_sub': 'Conecta tu perfil de LinkedIn para que te descubran marcas B2B.',
    'reg.creator_btn_linkedin': 'Continuar con LinkedIn',
    'reg.creator_btn_email': 'Continuar con correo corporativo',
    'reg.creator_terms': 'Al continuar, aceptas los Términos del servicio y la Política de privacidad de Naano.',

    'reg.creator_step2_title': 'Verifica los datos de tu perfil',
    'reg.creator_step2_sub': 'Extrajimos esto de tu LinkedIn. Puedes editar lo que desees.',
    'reg.lbl_name': 'Nombre público',
    'reg.lbl_headline': 'Titular profesional',
    'reg.lbl_followers': 'Tamaño de audiencia',
    'reg.lbl_topic': 'Tema principal',
    'reg.lbl_rate': 'Tarifa por post (€)',
    'reg.btn_continue_preview': 'Continuar a vista previa',

    'reg.creator_step3_title': 'Generando tu tarjeta de creador...',
    'reg.creator_step3_sub': 'Analizando tu perfil de LinkedIn y estadísticas de audiencia.',
    'reg.btn_enter_workspace': 'Entrar al panel',

    'reg.brand_step1_title': 'Crear cuenta de marca',
    'reg.brand_step1_sub': 'Accede a creadores B2B verificados y rastrea ingresos atribuidos.',
    'reg.brand_btn_google': 'Continuar con Google',
    'reg.lbl_work_email': 'Correo corporativo',
    'reg.lbl_company_name': 'Nombre de la empresa',
    'reg.lbl_company_website': 'Sitio web de la empresa',
    'reg.btn_continue_onboarding': 'Continuar al onboarding',

    'reg.brand_step2_title': 'Propuesta de valor e ICP',
    'reg.brand_step2_sub': 'Nuestra IA utiliza esto para emparejarte con los creadores ideales y generar briefs.',
    'reg.lbl_value_prop': '¿Qué hace tu producto? (Propuesta de valor)',
    'reg.lbl_target_audience': 'Audiencia objetivo / ICPs (Selecciona los que correspondan)',
    'reg.lbl_starter_brief': 'Brief inicial para creadores (Auto-generado)',
    'reg.btn_launch_matching': 'Buscar creadores afines',

    'reg.brand_step3_title': 'Emparejamiento de creadores en curso',
    'reg.brand_step3_sub': 'Analizando más de 4.800 perfiles B2B verificados que encajan con tu ICP.',
    'reg.btn_explore_dashboard': 'Entrar al panel de marca',

    'reg.card_preview_eyebrow': 'TU TARJETA DE MARKETPLACE',
    'reg.card_preview_title': 'Crea una tarjeta que genere confianza.',
    'reg.card_preview_copy': 'Se actualiza en tiempo real con tu perfil, métricas, posicionamiento y tarifas.',
    'reg.brand_stmt_title': 'Creadores. Marcas. Resultados.',
    'reg.brand_stmt_copy': 'Lanza campañas con creadores de LinkedIn que generen negocio real: descubre creadores, mide resultados y paga con un clic.',
    'reg.brand_stmt_sub': 'Diseñado para equipos de marketing B2B',
    'reg.lbl_url': 'URL de perfil de LinkedIn',
    'reg.brand_mic_query': '¿Qué te gustaría consultar?',

    // Login
    'login.tab_creator': 'Soy creador',
    'login.tab_brand': 'Soy una marca',
    'login.creator_title': 'Bienvenido de nuevo, Creador',
    'login.creator_sub': 'Inicia sesión para gestionar tu tarjeta, colaboraciones activas y cobros.',
    'login.brand_title': 'Bienvenida de nuevo, Marca',
    'login.brand_sub': 'Inicia sesión para gestionar tus briefs, campañas activas y analítica de pipeline.',
    'login.btn_linkedin': 'Continuar con LinkedIn',
    'login.btn_google': 'Continuar con Google',
    'login.signup_note': '¿Aún no tienes cuenta? <a href="/register" class="auth-signin-link" id="login-signup-link">Regístrate</a>',

    // Workspace
    'ws.back': 'Volver al onboarding',
    'ws.eyebrow': 'Panel de creador',
    'ws.title': 'Nos alegra verte, Waqar',
    'ws.subtitle': 'Tu actividad como creador, de un vistazo.',
    'ws.metric_reach': 'ALCANCE PÚBLICO',
    'ws.metric_reach_desc': 'Esperando datos de publicaciones',
    'ws.metric_posts': 'POSTS PÚBLICOS',
    'ws.metric_posts_desc': 'Publicaciones originales en LinkedIn',
    'ws.metric_eng': 'INTERACCIONES PÚBLICAS',
    'ws.metric_eng_desc': 'Reacciones, comentarios y reposts',
    'ws.metric_followers': 'SEGUIDORES EN LINKEDIN',
    'ws.metric_followers_desc': 'Importados del perfil público',
    'ws.card_title': 'Tu tarjeta de creador',
    'ws.card_sub': 'Así descubren las marcas tu posicionamiento y propuesta de colaboración.',
    'ws.btn_open': 'Abrir tarjeta',
    'ws.btn_copy': 'Copiar enlace',
    'ws.btn_share': 'Compartir mi tarjeta',
    'ws.badge_active': 'Creador activo',
    'ws.badge_top': 'Top 5% Interacción',
    'ws.guide_title': 'Guía de lanzamiento',
    'ws.guide_sub': '1 de 1 pasos completados',
    'ws.guide_step_title': 'Tarjeta y tarifas listas',
    'ws.guide_step_sub': 'Tu posicionamiento y oferta están listos para revisar.',
    'ws.guide_step_complete': 'Completado',
    'ws.collabs_title': 'Colaboraciones activas',
    'ws.collabs_sub': 'Todo lo que avanza desde el brief hasta la publicación.',
    'ws.collabs_empty': 'Sin colaboraciones activas.',
    'ws.collabs_see_all': 'Ver todo',
    'ws.collabs_th_brand': 'Marca',
    'ws.collabs_th_status': 'Estado',
    'ws.collabs_th_action': 'Siguiente acción',
    'ws.collabs_th_due': 'Plazo',
    'ws.collabs_th_net': 'Neto',
    'ws.opps_title': 'Oportunidades recomendadas',
    'ws.opps_sub': 'Las 3 campañas más afines a tu audiencia.',
    'ws.opps_explore': 'Explorar',
    'ws.opp_match_sub': 'Campaña principal · alta afinidad',
    'ws.card_no_data': 'Sin datos de posts disponibles',
    'ws.card_data_lbl': 'Datos',
    'ws.card_status_pending': 'Pendiente',
    'ws.card_stat_followers': 'Seguidores',
    'ws.card_stat_est_imp': 'Impresiones est.',
    'ws.card_stat_cost': 'Tarifa elegida',
    'ws.floating_assistant': '¿En qué puedo ayudarte?',
  },
};

/**
 * Targeted selector mapping rules
 */
const selectorRules = [
  // Navbar
  { sel: 'a[href="/"].nav-link', key: 'nav.for_companies' },
  { sel: 'a[href="/creators"].nav-link', key: 'nav.for_creators' },
  { sel: 'a[href="/agencies"].nav-link', key: 'nav.for_agencies' },
  { sel: 'a[href="/#how-it-works"].nav-link', key: 'nav.how_it_works' },
  { sel: '#resources-trigger > span', key: 'nav.resources' },
  { sel: '.nav-actions a[href="/login"]', key: 'nav.signin' },
  { sel: '.nav-actions a[href="/register"]', key: 'nav.signup' },
  { sel: '#resources-menu a[href="/blog"]', key: 'nav.res_pricing' },
  { sel: '#resources-menu a[href="/free-tools"]', key: 'nav.res_brief' },
  { sel: '#resources-menu a[href="/case-studies/blogseo"]', key: 'nav.res_cases' },
  { sel: '#resources-menu a[href="/reports"]', key: 'nav.res_reports' },

  // Mobile nav
  { sel: '.mobile-nav-panel a[href="/"]', key: 'nav.for_companies' },
  { sel: '.mobile-nav-panel a[href="/creators"]', key: 'nav.for_creators' },
  { sel: '.mobile-nav-panel a[href="/agencies"]', key: 'nav.for_agencies' },
  { sel: '.mobile-nav-panel a[href="/#how-it-works"]', key: 'nav.how_it_works' },
  { sel: '.mobile-actions a[href="/login"]', key: 'nav.signin' },
  { sel: '.mobile-actions a[href="/register"]', key: 'nav.signup' },

  // Hero
  { sel: '.hero-badge-text', key: 'hero.badge' },
  { sel: '#hero-heading', key: 'hero.title', html: true },
  { sel: '.hero-subtitle', key: 'hero.sub' },
  { sel: '.hero-btn-primary > span', key: 'hero.cta_primary' },
  { sel: '.hero-btn-secondary > span', key: 'hero.cta_secondary' },
  { sel: '.hero-trust-indicator > span', key: 'hero.trusted_by' },

  // Quote
  { sel: '.quote-author-role', key: 'quote.role' },
  { sel: '.quote-author-agency', key: 'quote.agency' },

  // Marketplace
  { sel: '.lp-marketplace__eyebrow', key: 'market.eyebrow' },
  { sel: '#lp-marketplace-title', key: 'market.title' },
  { sel: '.lp-marketplace__copy', key: 'market.copy' },
  { sel: '.lp-marketplace__signal--creators .lp-marketplace__signal-copy strong', key: 'market.signal1_title' },
  { sel: '.lp-marketplace__signal--creators .lp-marketplace__signal-copy span', key: 'market.signal1_sub' },
  { sel: '.lp-marketplace__signal--countries .lp-marketplace__signal-copy strong', key: 'market.signal2_title' },
  { sel: '.lp-marketplace__signal--countries .lp-marketplace__signal-copy span', key: 'market.signal2_sub' },
  { sel: '.lp-marketplace__signal--matching .lp-marketplace__signal-copy strong', key: 'market.signal3_title' },
  { sel: '.lp-marketplace__signal--matching .lp-marketplace__signal-copy span', key: 'market.signal3_sub' },

  // Proof / Case Study
  { sel: '.lp-proof-card--video .lp-proof-card__eyebrow', key: 'proof.video_eyebrow' },
  { sel: '.lp-proof-card--case .lp-proof-card__eyebrow', key: 'proof.case_eyebrow' },
  { sel: '#lp-testimonials-title', key: 'proof.title' },
  { sel: '.lp-testimonials-subtitle', key: 'proof.sub' },
  { sel: '.lp-proof-video__quote', key: 'proof.video_quote' },
  { sel: '.lp-proof-case-title', key: 'proof.case_title' },
  { sel: '.lp-proof-case-copy', key: 'proof.case_copy' },
  { sel: '.lp-cs-stat-col:nth-child(1) .lp-cs-stat-label', key: 'proof.stat1_label' },
  { sel: '.lp-cs-stat-col:nth-child(2) .lp-cs-stat-label', key: 'proof.stat2_label' },
  { sel: '.lp-cs-stat-col:nth-child(3) .lp-cs-stat-label', key: 'proof.stat3_label' },
  { sel: '.lp-cs-link > span', key: 'proof.read_case' },
  { sel: '.lp-trust-eyebrow', key: 'proof.trust_eyebrow' },

  // Results
  { sel: '.lp-results-eyebrow', key: 'results.eyebrow' },
  { sel: '#lp-results-title', key: 'results.title', html: true },
  { sel: '.lp-results-proof__stats .stat-pop:nth-child(1) > span', key: 'results.stat_imp' },
  { sel: '.lp-results-proof__stats .stat-pop:nth-child(2) > span', key: 'results.stat_leads' },
  { sel: '.lp-results-proof__stats .stat-pop:nth-child(3) > span', key: 'results.stat_creators' },
  { sel: '.lp-results-proof__stats .stat-pop:nth-child(4) > span', key: 'results.stat_posts' },
  { sel: '.lp-results-cta-btn > span', key: 'results.cta_btn' },
  { sel: '.lp-results-cta-sub', key: 'results.cta_sub' },

  // Pricing
  { sel: '#lp-pricing-title', key: 'pricing.title', html: true },
  { sel: '.lp-pricing-lead', key: 'pricing.lead' },
  { sel: '.lp-pricing-desc', key: 'pricing.desc' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__eyebrow', key: 'pricing.self_eyebrow' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__title', key: 'pricing.self_title' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__copy', key: 'pricing.self_copy' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__period', key: 'pricing.self_period' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__feature-item:nth-child(1)', key: 'pricing.self_f1' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__feature-item:nth-child(2)', key: 'pricing.self_f2' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__feature-item:nth-child(3)', key: 'pricing.self_f3' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__feature-item:nth-child(4)', key: 'pricing.self_f4' },
  { sel: '.lp-pricing-card--self .lp-pricing-card__link > span', key: 'pricing.self_cta' },

  { sel: '.lp-pricing-card--managed .lp-pricing-card__eyebrow', key: 'pricing.managed_eyebrow' },
  { sel: '.lp-pricing-card--managed .lp-pricing-card__title', key: 'pricing.managed_title' },
  { sel: '.lp-pricing-card--managed .lp-pricing-card__copy', key: 'pricing.managed_copy' },
  { sel: '.lp-pricing-card--managed .lp-pricing-card__amount', key: 'pricing.managed_cost' },
  { sel: '.lp-pricing-card--managed .lp-pricing-card__feature-item:nth-child(1)', key: 'pricing.managed_f1' },
  { sel: '.lp-pricing-card--managed .lp-pricing-card__feature-item:nth-child(2)', key: 'pricing.managed_f2' },
  { sel: '.lp-pricing-card--managed .lp-pricing-card__feature-item:nth-child(3)', key: 'pricing.managed_f3' },
  { sel: '.lp-pricing-card--managed .lp-pricing-card__feature-item:nth-child(4)', key: 'pricing.managed_f4' },
  { sel: '.lp-pricing-card--managed .lp-pricing-card__btn > span', key: 'pricing.managed_cta' },
  { sel: '.lp-pricing-footnote > span', key: 'pricing.footnote' },

  // FAQs
  { sel: '#lp-faq-title', key: 'faq.title', html: true },
  { sel: '.lp-faq-sub', key: 'faq.sub' },
  { sel: '.lp-faq-callout-lbl', key: 'faq.callout_lbl' },
  { sel: '.lp-faq-callout-link > span', key: 'faq.callout_link' },

  // Launch CTA
  { sel: '.lp-book-eyebrow', key: 'launch.eyebrow' },
  { sel: '.lp-book-title', key: 'launch.title' },
  { sel: '.lp-book-subtitle', key: 'launch.subtitle' },
  { sel: '.lp-book-host-badge', key: 'launch.badge' },
  { sel: '.lp-book-card-title', key: 'launch.card_title' },
  { sel: '.lp-book-card-desc', key: 'launch.card_desc' },
  { sel: '.lp-book-feature-item:nth-child(1) span:last-child', key: 'launch.feat_strategy' },
  { sel: '.lp-book-feature-item:nth-child(2) span:last-child', key: 'launch.feat_format' },
  { sel: '.lp-book-feature-item:nth-child(3) span:last-child', key: 'launch.feat_budget' },
  { sel: '.lp-book-cta > span', key: 'launch.cta_book' },
  { sel: '.lp-book-hint', key: 'launch.hint' },
  { sel: '.lp-book-secondary', key: 'launch.secondary', html: true },
  { sel: '.lp-book-footnote', key: 'launch.footnote' },

  // Footer
  { sel: '.lp-footer__tagline', key: 'footer.tagline' },
  { sel: '.lp-footer__col:nth-child(1) .lp-footer__col-title', key: 'footer.col_product' },
  { sel: '.lp-footer__col:nth-child(2) .lp-footer__col-title', key: 'footer.col_resources' },
  { sel: '.lp-footer__col:nth-child(3) .lp-footer__col-title', key: 'footer.col_company' },
  { sel: '.lp-footer__col:nth-child(4) .lp-footer__col-title', key: 'footer.col_legal' },
  { sel: '.lp-footer__copyright', key: 'footer.copyright' },

  // Register page
  { sel: '#view-role-select .auth-title', key: 'reg.title' },
  { sel: '#view-role-select .auth-subtitle', key: 'reg.sub' },
  { sel: '#role-card-creator .auth-role-title', key: 'reg.opt_creator_title' },
  { sel: '#role-card-creator .auth-role-desc', key: 'reg.opt_creator_desc' },
  { sel: '#role-card-brand .auth-role-title', key: 'reg.opt_brand_title' },
  { sel: '#role-card-brand .auth-role-desc', key: 'reg.opt_brand_desc' },
  { sel: '#view-role-select .auth-signin-note, #view-creator-auth .auth-signin-note, #view-brand-auth .auth-signin-note', key: 'reg.already_account', html: true },
  { sel: '#right-state-default .auth-statement-title', key: 'reg.stmt_title' },
  { sel: '#right-state-default .auth-statement-copy', key: 'reg.stmt_copy' },

  { sel: '#back-from-creator-auth span', key: 'reg.back_roles' },
  { sel: '#view-creator-auth .auth-step-badge', key: 'reg.step1_4' },
  { sel: '#view-creator-auth .auth-title', key: 'reg.creator_join_title' },
  { sel: '#view-creator-auth .auth-subtitle', key: 'reg.creator_join_sub' },
  { sel: '#btn-creator-oauth-linkedin span', key: 'reg.creator_btn_linkedin' },
  { sel: '#btn-creator-oauth-google span', key: 'reg.brand_btn_google' },
  { sel: '#btn-creator-oauth-email span', key: 'reg.creator_btn_email' },

  { sel: '#back-from-creator-profile span', key: 'reg.back_account' },
  { sel: '#view-creator-profile .auth-step-badge', key: 'reg.step2_4' },
  { sel: '#view-creator-profile .auth-title', key: 'reg.creator_step2_title' },
  { sel: '#view-creator-profile .auth-subtitle', key: 'reg.creator_step2_sub' },
  { sel: 'label[for="creator-input-url"]', key: 'reg.lbl_url' },
  { sel: 'label[for="creator-input-name"]', key: 'reg.lbl_name' },
  { sel: 'label[for="creator-input-tags"]', key: 'reg.lbl_topic' },
  { sel: 'label[for="creator-input-price"]', key: 'reg.lbl_rate' },
  { sel: '#btn-submit-creator-profile span', key: 'reg.btn_continue_preview' },

  { sel: '#view-creator-sync .auth-step-badge', key: 'reg.step3_4' },
  { sel: '#view-creator-sync .auth-title', key: 'reg.creator_step3_title' },
  { sel: '#view-creator-sync .auth-subtitle', key: 'reg.creator_step3_sub' },
  { sel: '#view-creator-complete .auth-step-badge', key: 'reg.step4_4' },
  { sel: '#btn-enter-workspace span', key: 'reg.btn_enter_workspace' },

  { sel: '#back-from-brand-auth span', key: 'reg.back_roles' },
  { sel: '#view-brand-auth .auth-title', key: 'reg.brand_step1_title' },
  { sel: '#view-brand-auth .auth-subtitle', key: 'reg.brand_step1_sub' },
  { sel: '#btn-brand-oauth-linkedin span', key: 'reg.creator_btn_linkedin' },
  { sel: '#btn-brand-oauth-google span', key: 'reg.brand_btn_google' },
  { sel: '#btn-brand-oauth-email span', key: 'reg.creator_btn_email' },

  { sel: '#back-from-brand-onboarding', key: 'reg.back_details' },
  { sel: '#view-brand-onboarding .brand-step-text', key: 'reg.step2_3' },
  { sel: '.brand-id-title', key: 'reg.brand_step2_title' },
  { sel: '.brand-id-sub', key: 'reg.brand_step2_sub' },
  { sel: '.brand-section:nth-of-type(1) .brand-section-eyebrow', key: 'reg.lbl_value_prop' },
  { sel: '#btn-continue-ai-matching', key: 'reg.btn_launch_matching' },

  { sel: '#view-brand-matching .brand-step-text', key: 'reg.step3_3' },
  { sel: '#view-brand-matching .auth-title', key: 'reg.brand_step3_title' },
  { sel: '#view-brand-matching .auth-subtitle', key: 'reg.brand_step3_sub' },
  { sel: '#btn-brand-dashboard span', key: 'reg.btn_explore_dashboard' },

  // Login page
  { sel: '#tab-login-creator', key: 'login.tab_creator' },
  { sel: '#tab-login-brand', key: 'login.tab_brand' },
  { sel: '#login-view-creator .auth-title', key: 'login.creator_title' },
  { sel: '#login-view-creator .auth-subtitle', key: 'login.creator_sub' },
  { sel: '#btn-login-creator-linkedin span', key: 'login.btn_linkedin' },
  { sel: '#btn-login-creator-google span', key: 'login.btn_google' },
  { sel: '#login-view-brand .auth-title', key: 'login.brand_title' },
  { sel: '#login-view-brand .auth-subtitle', key: 'login.brand_sub' },
  { sel: '#btn-login-brand-google span', key: 'login.btn_google' },
  { sel: '#btn-login-brand-linkedin span', key: 'login.btn_linkedin' },
  { sel: '#login-signup-note', key: 'login.signup_note', html: true },

  // Register right side states
  { sel: '#right-state-creator .auth-preview-eyebrow', key: 'reg.card_preview_eyebrow' },
  { sel: '#right-state-creator .auth-preview-title', key: 'reg.card_preview_title' },
  { sel: '#right-state-creator .auth-preview-copy', key: 'reg.card_preview_copy' },
  { sel: '#right-state-brand .auth-statement-title', key: 'reg.brand_stmt_title' },
  { sel: '#right-state-brand .auth-statement-copy', key: 'reg.brand_stmt_copy' },
  { sel: '#right-state-brand .auth-statement-sub', key: 'reg.brand_stmt_sub' },
  { sel: '#brand-floating-assistant span', key: 'reg.brand_mic_query' },

  // Workspace
  { sel: '.ws-back-register span', key: 'ws.back' },
  { sel: '.ws-eyebrow', key: 'ws.eyebrow' },
  { sel: '.ws-title', key: 'ws.title' },
  { sel: '.ws-subtitle', key: 'ws.subtitle' },
  { sel: '.ws-metric-card:nth-child(1) .ws-metric-label', key: 'ws.metric_reach' },
  { sel: '.ws-metric-card:nth-child(1) .ws-metric-desc', key: 'ws.metric_reach_desc' },
  { sel: '.ws-metric-card:nth-child(2) .ws-metric-label', key: 'ws.metric_posts' },
  { sel: '.ws-metric-card:nth-child(2) .ws-metric-desc', key: 'ws.metric_posts_desc' },
  { sel: '.ws-metric-card:nth-child(3) .ws-metric-label', key: 'ws.metric_eng' },
  { sel: '.ws-metric-card:nth-child(3) .ws-metric-desc', key: 'ws.metric_eng_desc' },
  { sel: '.ws-metric-card:nth-child(4) .ws-metric-label', key: 'ws.metric_followers' },
  { sel: '.ws-metric-card:nth-child(4) .ws-metric-desc', key: 'ws.metric_followers_desc' },
  { sel: '.ws-panel-title', key: 'ws.card_title' },
  { sel: '.ws-panel-sub', key: 'ws.card_sub' },
  { sel: '#btn-open-card span', key: 'ws.btn_open' },
  { sel: '#btn-copy-link span', key: 'ws.btn_copy' },
  { sel: '#btn-share-card span', key: 'ws.btn_share' },
  { sel: '.ws-guide-panel .ws-panel-title', key: 'ws.guide_title' },
  { sel: '.ws-guide-panel .ws-panel-sub', key: 'ws.guide_sub' },
  { sel: '.ws-guide-panel .ws-link-blue', key: 'ws.btn_open' },
  { sel: '.ws-guide-title', key: 'ws.guide_step_title' },
  { sel: '.ws-guide-sub', key: 'ws.guide_step_sub' },
  { sel: '.ws-pill-complete', key: 'ws.guide_step_complete' },
  { sel: '.ws-collabs-panel .ws-panel-title', key: 'ws.collabs_title' },
  { sel: '.ws-collabs-panel .ws-panel-sub', key: 'ws.collabs_sub' },
  { sel: '.ws-collabs-panel .ws-link-blue', key: 'ws.collabs_see_all' },
  { sel: '.ws-collabs-empty', key: 'ws.collabs_empty' },
  { sel: '.ws-collabs-table-header span:nth-child(1)', key: 'ws.collabs_th_brand' },
  { sel: '.ws-collabs-table-header span:nth-child(2)', key: 'ws.collabs_th_status' },
  { sel: '.ws-collabs-table-header span:nth-child(3)', key: 'ws.collabs_th_action' },
  { sel: '.ws-collabs-table-header span:nth-child(4)', key: 'ws.collabs_th_due' },
  { sel: '.ws-collabs-table-header span:nth-child(5)', key: 'ws.collabs_th_net' },
  { sel: '.ws-opportunities-panel .ws-panel-title', key: 'ws.opps_title' },
  { sel: '.ws-opportunities-panel .ws-panel-sub', key: 'ws.opps_sub' },
  { sel: '.ws-opportunities-panel .ws-link-blue', key: 'ws.opps_explore' },
  { sel: '.ws-opp-item:nth-child(1) .ws-opp-sub', key: 'ws.opp_match_sub' },
  { sel: '.ws-opp-item:nth-child(2) .ws-opp-sub', key: 'ws.opp_match_sub' },
  { sel: '.ws-card-calendar-badge span', key: 'ws.card_no_data' },
  { sel: '.ws-card-progress-label', key: 'ws.card_data_lbl' },
  { sel: '.ws-card-progress-status', key: 'ws.card_status_pending' },
  { sel: '.ws-card-stat-col:nth-child(1) .ws-card-stat-title', key: 'ws.card_stat_followers' },
  { sel: '.ws-card-stat-col:nth-child(2) .ws-card-stat-title', key: 'ws.card_stat_est_imp' },
  { sel: '.ws-card-stat-col:nth-child(3) .ws-card-stat-title', key: 'ws.card_stat_cost' },
  { sel: '.ws-ai-input', attr: 'placeholder', key: 'ws.floating_assistant' },
];

/**
 * Get current persisted language ('EN' or 'ES')
 */
export function getLanguage() {
  const saved = localStorage.getItem(STORAGE_KEY);
  return saved === 'ES' ? 'ES' : 'EN';
}

/**
 * Translate a specific key
 */
export function t(key) {
  const lang = getLanguage();
  return translations[lang]?.[key] ?? translations.EN?.[key] ?? key;
}

/**
 * Update quote section scroll reveal words
 */
function updateQuoteWords(lang) {
  const quoteElem = document.querySelector('.quote-text');
  if (!quoteElem) return;

  const enWords = [
    'We ', 'manage ', '€10M+ ', 'of ', 'influence ', 'budget ',
    'every ', 'year. ', 'For ', 'B2B, ', 'Naano ', 'simply ', 'makes ', 'our ', 'life ', 'easier'
  ];

  const esWords = [
    'Gestionamos ', 'más ', 'de ', '10M€ ', 'en ', 'presupuesto ',
    'de ', 'influencia ', 'cada ', 'año. ', 'Para ', 'B2B, ', 'Naano ', 'simplemente ', 'nos ', 'facilita ', 'la ', 'vida'
  ];

  const words = lang === 'ES' ? esWords : enWords;
  quoteElem.innerHTML = '“' + words.map((w, idx) => {
    const isLast = idx === words.length - 1;
    const cls = isLast ? 'quote-word quote-word-accent' : 'quote-word';
    return `<span data-qw="${idx}" class="${cls}">${w}</span>`;
  }).join('') + '”';

  // Trigger scroll re-calc if scroll handler active
  window.dispatchEvent(new Event('scroll'));
}

/**
 * Update FAQ questions and answers
 */
function updateFaqs(lang) {
  for (let i = 1; i <= 8; i++) {
    const item = document.querySelector(`.lp-faq-item:nth-child(${i})`);
    if (!item) continue;
    const q = item.querySelector('.lp-faq-q');
    const a = item.querySelector('.lp-faq-a');
    const qText = translations[lang]?.[`faq.q${i}`];
    const aText = translations[lang]?.[`faq.a${i}`];
    if (q && qText) q.textContent = qText;
    if (a && aText) a.textContent = aText;
  }
}

/**
 * Update results grid post card labels
 */
function updateResultCards(lang) {
  document.querySelectorAll('.lp-post-card').forEach((card) => {
    const impLbl = card.querySelector('.lp-metric-item:nth-child(1) .lp-metric-lbl');
    const clkLbl = card.querySelector('.lp-metric-item:nth-child(2) .lp-metric-lbl');
    const leadLbl = card.querySelector('.lp-metric-item:nth-child(3) .lp-metric-lbl');
    const forLbl = card.querySelector('.lp-post-for-lbl');
    const linkSpan = card.querySelector('.lp-post-view-link > span');

    if (impLbl) impLbl.textContent = lang === 'ES' ? 'Impresiones' : 'Impressions';
    if (clkLbl) clkLbl.textContent = lang === 'ES' ? 'Clics' : 'Clicks';
    if (leadLbl) leadLbl.textContent = lang === 'ES' ? 'Leads' : 'Leads';
    if (forLbl) forLbl.textContent = lang === 'ES' ? 'Para' : 'For';
    if (linkSpan) linkSpan.textContent = lang === 'ES' ? 'Ver publicación' : 'View post';
  });
}

/**
 * Synchronize UI elements with current language
 */
export function applyCurrentLanguage() {
  const lang = getLanguage();
  document.documentElement.lang = lang.toLowerCase();

  // 1. Elements with data-i18n
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    const val = translations[lang]?.[key];
    if (val !== undefined) {
      el.textContent = val;
    }
  });

  // 2. Elements with data-i18n-html
  document.querySelectorAll('[data-i18n-html]').forEach((el) => {
    const key = el.getAttribute('data-i18n-html');
    const val = translations[lang]?.[key];
    if (val !== undefined) {
      el.innerHTML = val;
    }
  });

  // 3. Inputs with data-i18n-placeholder
  document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
    const key = el.getAttribute('data-i18n-placeholder');
    const val = translations[lang]?.[key];
    if (val !== undefined) {
      el.setAttribute('placeholder', val);
    }
  });

  // 4. Selector-level mapping rules
  selectorRules.forEach((rule) => {
    const el = document.querySelector(rule.sel);
    if (el) {
      const text = translations[lang]?.[rule.key];
      if (text !== undefined) {
        if (rule.attr) {
          el.setAttribute(rule.attr, text);
        } else if (rule.html) {
          el.innerHTML = text;
        } else {
          el.textContent = text;
        }
      }
    }
  });

  // 5. Section specific helpers
  updateQuoteWords(lang);
  updateFaqs(lang);
  updateResultCards(lang);

  // 6. Update toggles state
  updateToggleButtons(lang);
}

/**
 * Update all language toggle buttons and active labels across current page
 */
export function updateToggleButtons(lang) {
  // Active text codes
  const activeCodes = document.querySelectorAll(
    '#active-lang, .mobile-lang-code, .auth-lang-code'
  );
  activeCodes.forEach((el) => {
    el.textContent = lang;
    el.classList.remove('animate-change');
    void el.offsetWidth;
    el.classList.add('animate-change');
  });

  // Aria labels
  const toggleButtons = document.querySelectorAll(
    '#lang-toggle-btn, .mobile-lang-toggle, #auth-lang-btn'
  );
  toggleButtons.forEach((btn) => {
    btn.setAttribute(
      'aria-label',
      lang === 'EN'
        ? 'Switch language, current English'
        : 'Cambiar idioma, actual Español'
    );
  });

  // Workspace EN / ES pill
  const wsEn = document.getElementById('ws-lang-en');
  const wsEs = document.getElementById('ws-lang-es') || document.getElementById('ws-lang-fr');
  if (wsEn && wsEs) {
    if (lang === 'EN') {
      wsEn.classList.add('is-active');
      wsEs.classList.remove('is-active');
    } else {
      wsEs.classList.add('is-active');
      wsEn.classList.remove('is-active');
    }
  }
}

/**
 * Set active language and trigger update
 */
export function setLanguage(newLang) {
  const normalized = newLang === 'ES' ? 'ES' : 'EN';
  localStorage.setItem(STORAGE_KEY, normalized);
  applyCurrentLanguage();

  window.dispatchEvent(
    new CustomEvent('languagechange', { detail: { lang: normalized } })
  );
}

/**
 * Toggle between EN and ES
 */
export function toggleLanguage() {
  const nextLang = getLanguage() === 'EN' ? 'ES' : 'EN';
  setLanguage(nextLang);
  return nextLang;
}

/**
 * Initialize i18n controller and bind click handlers
 */
export function initI18n() {
  // Desktop toggle button
  const desktopBtn = document.getElementById('lang-toggle-btn');
  if (desktopBtn && !desktopBtn.dataset.i18nBound) {
    desktopBtn.dataset.i18nBound = 'true';
    desktopBtn.addEventListener('click', (e) => {
      e.preventDefault();
      toggleLanguage();
    });
  }

  // Mobile toggle button
  const mobileBtn = document.querySelector('.mobile-lang-toggle');
  if (mobileBtn && !mobileBtn.dataset.i18nBound) {
    mobileBtn.dataset.i18nBound = 'true';
    mobileBtn.addEventListener('click', (e) => {
      e.preventDefault();
      toggleLanguage();
    });
  }

  // Register page auth language button
  const authBtn = document.getElementById('auth-lang-btn');
  if (authBtn && !authBtn.dataset.i18nBound) {
    authBtn.dataset.i18nBound = 'true';
    authBtn.addEventListener('click', (e) => {
      e.preventDefault();
      toggleLanguage();
    });
  }

  // Workspace pill buttons
  const wsEn = document.getElementById('ws-lang-en');
  const wsEs = document.getElementById('ws-lang-es') || document.getElementById('ws-lang-fr');
  if (wsEn && !wsEn.dataset.i18nBound) {
    wsEn.dataset.i18nBound = 'true';
    wsEn.addEventListener('click', () => setLanguage('EN'));
  }
  if (wsEs && !wsEs.dataset.i18nBound) {
    wsEs.dataset.i18nBound = 'true';
    wsEs.addEventListener('click', () => setLanguage('ES'));
  }

  // Cross-tab storage synchronization
  window.addEventListener('storage', (e) => {
    if (e.key === STORAGE_KEY) {
      applyCurrentLanguage();
    }
  });

  // Apply initial persisted language
  applyCurrentLanguage();
}
